### PR TITLE
Bring forth develop

### PR DESCRIPTION
**Pull request by RandomDev26**
I tried bring develop up to main, tell me if I did something wrong

### CODE REVIEW

**Comment by fisher60** [comment]
I have not had a chance to review this properly, but I can see that the build is failing. Please look fix this issue and ensure the check passes.

**Comment by RandomDev26** [comment]
The test says that it expects "/Gurkan/i" to be in the document, but the only instance I can find of it on the main branch is in the app.test.js, nowhere else, so where is it supposed to be?

**Comment by mudkipdev** [comment]
> The test says that it expects "/Gurkan/i" to be in the document, but the only instance I can find of it on the main branch is in the app.test.js, nowhere else, so where is it supposed to be?

you have to find it on the dev branch

**Comment by Atharv-Attri** [comment]
> you have to find it on the dev branch

I tried, couldn't find it there either.

**Pull request merged**
