### PR TITLE
Added discord invite to the parking page

### PR DESCRIPTION
**Pull request by zeeshanok**

### CODE REVIEW

**Review by gustavwilliam — APPROVED** [review]
LGTM.

**Review by fisher60 — CHANGES_REQUESTED** [review]
Please see how we handled other links on this component. It is not good practice to ignore warnings from react.

**Comment by zeeshanok** [comment]
Do you mean the `target="_blank" rel="noopener noreferrer"` attributes?

**Comment by fisher60** [comment]
Thank you for this contribution, we are actually trying to stray away from the default parking page, so I am going to go with the other PR for the discord invite that uses a router.

**Pull request closed without merging**
